version: "3.3"

services:
  postgres:
    build: ./database/postgres
    image: appsec-postgres:001
    env_file: .env
    networks:
      - dbnet
      - migrationnet
    ports:
      - "5432:5432"
  migrations:
    image: "node:13"
    env_file: .env
    working_dir: /home/node/app/migration-manager
    depends_on: 
      - postgres
    networks:
      - migrationnet
    volumes:
      - ./database:/home/node/app
    entrypoint: "/home/node/app/migration-manager/scripts/entrypoint.sh"
  application:
    image: "node:13"
    env_file: .env
    working_dir: /home/node/webapp
    depends_on: 
      - postgres
      - migrations
    networks:
      - appnet
      - dbnet
    ports:
      - "8080:3000"
    volumes:
      - ./application:/home/node/webapp
    entrypoint: "/home/node/webapp/scripts/entrypoint.sh"

networks:
  dbnet:
  appnet:
  migrationnet: